os: osx

language: objective-c
osx_image: xcode10.1
xcode_workspace: Planted.xcworkspace
cache:
    - bundler
    - cocoapods
install:
    - bundle install
    - bundle exec pod install --repo-update
script:
    - bundle exec fastlane test
branches:
  only:
  - master
